### ISSUE TITLE
"Invalid token format" error returned when using malformed auth code

### ISSUE THREAD

**Issue by jabcreations** [gsuitedevs/php-samples#12]
(Please search [existing issues](https://github.com/gsuitedevs/php-samples/issues) before creating a new one.)

**Sample:**

## Expected Behavior
Not sure.

## Actual Behavior
This error_log file was created:

[] PHP Fatal error:  Uncaught InvalidArgumentException: Invalid token format in /home/example1/public_html/temp/calendar/vendor/google/apiclient/src/Google/Client.php:433
Stack trace:
#0 /home/example1/public_html/temp/calendar/quickstart.php(39): Google_Client->setAccessToken(Array)
#1 /home/example1/public_html/temp/calendar/quickstart.php(52): getClient()
#2 {main}
  thrown in /home/example1/public_html/temp/calendar/vendor/google/apiclient/src/Google/Client.php on line 433
[] PHP Fatal error:  Uncaught InvalidArgumentException: Invalid token format in /home/example1/public_html/temp/calendar/vendor/google/apiclient/src/Google/Client.php:433
Stack trace:
#0 /home/example1/public_html/temp/calendar/quickstart.php(39): Google_Client->setAccessToken(Array)
#1 /home/example1/public_html/temp/calendar/quickstart.php(52): getClient()
#2 {main}
  thrown in /home/example1/public_html/temp/calendar/vendor/google/apiclient/src/Google/Client.php on line 433

## Steps to Reproduce the Problem

  1. Follow this tutorial using PuTTY: https://developers.google.com/calendar/quickstart/php
  2. When you need to copy the URL select it and right click to copy, THAT triggers the error (apparently).

## Specifications

  - PHP version (`php -v`): 7.0.31
  - OS (Mac/Linux/Windows): Linux

Apparently the tutorial did work as the second time I run _php quickstart.php_ PuTTY displays a list of near-future events from Google Calendar.

**Comment by erickoledadevrel** [comment]
The problem seems to be that you inadvertently entered an invalid auth code, but the error wasn't clear about that. I'll have a fix out soon.
