### ISSUE TITLE
Thank you!!!!!

### ISSUE THREAD

**Issue by andriy159** [gsuitedevs/php-samples#17]
It Works!
I wanted to see the protocol as everything works in detail, but the directory did not find such information. I think the conversion code itself could fit in a couple of lines of the program, but I did not succeed because I do not know the protocol. I got closer to the truth but the SSL connection could not be promoted. So you had to use your ready code and this code works! Thank you! It was a bit difficult, because I do not know English perfectly, but I did everything perfectly.

**Comment by erickoledadevrel** [comment]
Glad you got it working!
