### ISSUE TITLE
Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by ZerosDev** [gsuitedevs/php-samples#19]
Hi, i tried to run the quickstart.php and got this error

PHP Warning:  count(): Parameter must be an array or an object that implements Countable in F:\xampp\htdocs\google-group
\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 67

Warning: count(): Parameter must be an array or an object that implements Countable in F:\xampp\htdocs\google-group\vend
or\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 67
Credentials saved to token.json

**Comment by grant** [comment]
Sorry for the troubles @ZerosDev, which sample this referring to? What PHP version are you using?

**Comment by arifamd00** [comment]
Hi Sir,
I am facing following error after entering verification code. I am using PHP 7.2.4 please help me.

"Warning: count(): Parameter must be an array or an object that implements Countable in C:\wamp64\www\My Project\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 67

Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\wamp64\www\My Project\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187
Stack trace:
#0 C:\wamp64\www\My Project\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 C:\wamp64\www\My Project\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 C:\wamp64\www\My Project\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 C:\wamp64\www\My Project\vendor\guzzlehttp\guzzle\src\Handler\Pro in C:\wamp64\www\My Project\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187"

**Comment by nanophp** [comment]
I got same error. I'm using php version 7.2.7. How can I fix this problem?

**Comment by Gurpreet-bnl** [comment]
Hello Sir,
           i got same problem please help what can i do.???? i'm using PHP 7.2.4 window 10

Warning: count(): Parameter must be an array or an object that implements Countable in E:\wamp\www\calendar\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 67

Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in E:\wamp\www\calendar\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187
Stack trace:
#0 E:\wamp\www\calendar\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 E:\wamp\www\calendar\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 E:\wamp\www\calendar\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 E:\wamp\www\calendar\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(28): GuzzleHt in E:\wamp\www\calendar\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187

**Comment by erickoledadevrel** [comment]
The message about `count()` is just a warning, and something that should go away once the PHP library upgrades to a new version of Guzzle. The SSL error is a blocker though, so I've updated the issue title to match.

**Comment by erickoledadevrel** [comment]
This error indicates that the underlying HTTP libraries can't find a certificate store, and are therefore unable to setup the SSL connection to Google's servers. See the [Guzzle library's documentation](http://docs.guzzlephp.org/en/stable/request-options.html#verify-option) for information on how to setup a certificate store on your machine.

I've added a troubleshooting section to our PHP quickstarts with the same information:

https://developers.google.com/sheets/api/quickstart/php#troubleshooting

**Comment by rogerfsg** [comment]
The link to the SSL configuration is on on GuzzlePHP docs
http://docs.guzzlephp.org/en/stable/request-options.html#verify-option
