### ISSUE TITLE
Fatal error: Uncaught InvalidArgumentException

### ISSUE THREAD

**Issue by SamMalcolm** [gsuitedevs/php-samples#20]
(Please search [existing issues](https://github.com/gsuitedevs/php-samples/issues) before creating a new one.)

**Sample:**

## Expected Behavior

- Fowarded to website to approve access to gapi

## Actual Behavior

Terminal throws an error:
 Fatal error: Uncaught InvalidArgumentException: missing the required redirect URI in /Users/e32398/Sites/composer_test/vendor/google/auth/src/OAuth2.php:650
Stack trace:
#0 /Users/e32398/Sites/composer_test/vendor/google/apiclient/src/Google/Client.php(339): Google\Auth\OAuth2->buildFullAuthorizationUri(Array)
#1 /Users/e32398/Sites/composer_test/quickstart.php(26): Google_Client->createAuthUrl()
#2 /Users/e32398/Sites/composer_test/quickstart.php(58): getClient()
#3 {main}
  thrown in /Users/e32398/Sites/composer_test/vendor/google/auth/src/OAuth2.php on line 650

## Steps to Reproduce the Problem

  1. Installed composer and composer packages
  1. created credentials in API console selecting server side access. Created user for credentials as project owner
  1. Copy php to quickstart.php and ran php quickstart.php

## Specifications

  - PHP version (`php -v`): 7.1.7
  - OS (Mac/Linux/Windows): 10.13.1

**Comment by asrivas** [comment]
Which quickstart is this from?

**Comment by bshaffer** [comment]
Hello! So you will need to set the redirect URI in your `Google_Client` instance before calling `createAuthUrl`. For example:

```php
$client = new Google_Client();
$client->setRedirectUri('https://mywebsite.com/auth/callback');
$client->setAuthConfig('/path/to/service_account.json');
$url = $client->createAuthUrl();
```

**Comment by SamMalcolm** [comment]
@asrivas  PHP Quickstart for the google sheets api v4

**Comment by SamMalcolm** [comment]
I had download an incorrectly configured crednetials.json file as i must have selected the wront prefrences. As suchh im closing this issue, thanks for your input @asrivas  and @bshaffer
