### ISSUE TITLE
Missing required parameter: scope

### ISSUE THREAD

**Issue by gregfr** [gsuitedevs/php-samples#26]
I've followed step by step this tutorial here:
https://developers.google.com/sheets/api/quickstart/php
When opening the given URL, I see this error:

400. That’s an error.
Error: invalid_request
Missing required parameter: scope

If I add a scope parameter ("https://www.googleapis.com/auth/plus.login") to the URL manually, I get this error:

400. That’s an error.
Error: invalid_request
Invalid parameter value for redirect_uri: Missing authority: urn:ietf:w

Why are these parameters missing? how can I have a proper URL generated?

Thanks in advance

## Expected Behavior

URL gives a login screen

## Actual Behavior

URL gives a 400 error

## Steps to Reproduce the Problem

  1. Follow the tutorial
  1. Click on the URL provided
 

## Specifications

  - PHP version (`php -v`): PHP 7.0.32-0ubuntu0.16.04.1 (cli) ( NTS )
  - OS (Mac/Linux/Windows): Ubuntu 16.04.5 LTS

**Comment by erickoledadevrel** [comment]
Not sure there is anything we can do to prevent this, the OAuth approval URL is rather long. Let me know if you have any ideas.
