### ISSUE TITLE
Missing required redirect 

### ISSUE THREAD

**Issue by roenschg** [gsuitedevs/php-samples#32]
I have to reopen that issue which is related to #22 

The issue was closed but it was still an error! There is missing one line in the example file:
`$client->setRedirectUri(...);`

Please change the documentation accordingly.

## Expected Behavior
I can access the API

## Actual Behavior
I see an error because the redirect uri for OAuth is not defined.
`In OAuth2.php line 650:
                                     
missing the required redirect URI`

## Steps to Reproduce the Problem

  1. Start the script
  2. See the error

## Specifications

  - PHP version 7.2
  - OS Mac OSX

**Comment by erickoledadevrel** [comment]
As mentioned in that issue, if you download credentials for an "Installed application" client ID, the redirect URI will be set automatically. This error should only happen if you use web application credentials. Can you confirm that you downloaded the correct credential type?

**Comment by seeker1983** [comment]
Makes sense. Yeap, I used web app, so this one's invalid. Thanks for your
reply and clarification. I used my already existing project, and didn't
knew about this issue.

пт, 21 дек. 2018 г., 21:14 Eric Koleda notifications@github.com:
