### ISSUE TITLE
Problem with quickstart

### ISSUE THREAD

**Issue by bhaktatejas922** [gsuitedevs/php-samples#35]
Quickstart just doesnt work, followed all the steps, got the link, entered the verification code, but I just get a blank terminal after running. Using php 7.2, tried it in the command line
![error](https://user-images.githubusercontent.com/26863466/51279159-6a8ba600-1991-11e9-8b89-f17c6e4787fa.png)

**Comment by erickoledadevrel** [comment]
Very strange, I'm not able to replicate that, or see a code path that would lead to that output. Have you tried debugging the code at all to see where it fails?

**Comment by bhaktatejas922** [comment]
If you have PhpStorm, are you able to replicate it on there?

**Comment by bhaktatejas922** [comment]
![image](https://user-images.githubusercontent.com/26863466/51432878-ff8dd980-1bf3-11e9-92a9-44f2fda436b1.png)

**Comment by erickoledadevrel** [comment]
I don't use PhpStorm, do you think the failure is specific to that IDE? I'm not sure what you are trying to demonstrate in the screenshot, can you clarify?

**Comment by bhaktatejas922** [comment]
I just wanted to show the "errors" my IDE picked up, in case it helps. It said "Expected array, got string" for that part. Not sure if that means there was an issue at an earlier step or what.

**Comment by erickoledadevrel** [comment]
Glad you got it working!
