### ISSUE TITLE
guzzlehttp error

### ISSUE THREAD

**Issue by Jaminb2030** [gsuitedevs/php-samples#37]
Enter verification code: 4/2wADbs9_wqAJ****1 2 Skip a few*****QwZ9NNvlSWfSy5
gU
PHP Warning:  count(): Parameter must be an array or an object that implements C
ountable in C:\xampp\composer\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.p
hp on line 67

Warning: count(): Parameter must be an array or an object that implements Counta
ble in C:\xampp\composer\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on
 line 67
Name, Major:
Alexandra, English
Andrew, Math
Anna, English
Becky, Art
Benjamin, English
Carl, Art
Carrie, English
Dorothy, Math
Dylan, Math
Edward, English
Ellen, Physics
Fiona, Art
John, Physics
Jonathan, Math
Joseph, English
Josephine, Math
Karen, English
Kevin, Physics
Lisa, Art
Mary, Physics
Maureen, Physics
Nick, Art
Olivia, Physics
Pamela, Math
Patrick, Art
Robert, English
Sean, Physics
Stacy, Math
Thomas, Art
Will, Math

C:\xampp\composer\vendor>

**Comment by erickoledadevrel** [comment]
Please follow issue #29 instead.
