### ISSUE TITLE
Invalid JSON payload received when using null in update function.

### ISSUE THREAD

**Issue by Latiyan** [gsuitedevs/php-samples#39]
Here in the doc: https://developers.google.com/sheets/api/samples/writing#write_selectively_to_a_range

It's mentioned that we can pass null value if we do not want to update the cell and leave it as it is. 

But it throws me an error "Invalid JSON payload received.", refer: http://bakingcode.org/hitesh/2019-17-25-07.png

Can you please help.

**Comment by erickoledadevrel** [comment]
This issue tracker is for bugs in the sample code. For issues with the API itself please see the support page:

https://developers.google.com/sheets/api/support

FWIW, I just tried passing a null in the "Try this API" sidebar [here](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/update) and it worked fine.

**Comment by rendragnet** [comment]
@Latiyan Did you sort this out? It seems to still be a bug in the google PHP API library :(
