### ISSUE TITLE
Fatal error: Class 'Google_Service_Docs' not found

### ISSUE THREAD

**Issue by theamaesf** [gsuitedevs/php-samples#41]
(Please search [existing issues](https://github.com/gsuitedevs/php-samples/issues) before creating a new one.)

**Sample:**

## Expected Behavior
To be able to proceed to step 4 of the quickstart guide ( https://developers.google.com/docs/api/quickstart/php )

## Actual Behavior
This error appears.

## Steps to Reproduce the Problem

  1. Just run the tutorial as stated.

## Specifications

  - PHP version (`php -v`): PHP 5.6.30
  - OS (Mac/Linux/Windows): Mac

**Comment by erickoledadevrel** [comment]
You need to update to the latest version of the library, as the Google Docs API classes don't exist in the order versions. Run `composer update google/apiclient`.

**Comment by sianghung** [comment]
@erickoledadevrel I am sure I have the latest version but still there is not Google Docs API classes in the library.

**Comment by sianghung** [comment]
Sorry, I got it now, I had to remove the whole vendor folder and run composer update again.
