### ISSUE TITLE
Count warning

### ISSUE THREAD

**Issue by jabbergabber** [gsuitedevs/php-samples#43]
(Please search [existing issues](https://github.com/gsuitedevs/php-samples/issues) before creating a new one.)

**Sample:**

## Expected Behavior
return spreadsheet details without warnings

## Actual Behavior
returned spreadsheet details but with warnings

PHP Warning:  count(): Parameter must be an array or an object that implements Countable in C:\inetpub\wwwroot\google-sheet-api\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 67
PHP Stack trace:
PHP   1. {main}() C:\inetpub\wwwroot\google-sheet-api\quickstart.php:0
PHP   2. Google_Service_Sheets_Resource_SpreadsheetsValues->get() C:\inetpub\wwwroot\google-sheet-api\quickstart.php:70
PHP   3. Google_Service_Sheets_Resource_SpreadsheetsValues->call() C:\inetpub\wwwroot\google-sheet-api\vendor\google\apiclient-services\src\Google\Service\Sheets\Resource\SpreadsheetsValues.php:222
PHP   4. Google_Client->execute() C:\inetpub\wwwroot\google-sheet-api\vendor\google\apiclient\src\Google\Service\Resource.php:232
PHP   5. Google_Http_REST::execute() C:\inetpub\wwwroot\google-sheet-api\vendor\google\apiclient\src\Google\Client.php:779
PHP   6. Google_Task_Runner->run() C:\inetpub\wwwroot\google-sheet-api\vendor\google\apiclient\src\Google\Http\REST.php:58
PHP   7. Google_Http_REST::doExecute() C:\inetpub\wwwroot\google-sheet-api\vendor\google\apiclient\src\Google\Task\Runner.php:181
PHP   8. Google\Auth\HttpHandler\Guzzle6HttpHandler->__invoke() C:\inetpub\wwwroot\google-sheet-api\vendor\google\apiclient\src\Google\Http\REST.php:74
PHP   9. GuzzleHttp\Client->send() C:\inetpub\wwwroot\google-sheet-api\vendor\google\auth\src\HttpHandler\Guzzle6HttpHandler.php:34
PHP  10. GuzzleHttp\Client->sendAsync() C:\inetpub\wwwroot\google-sheet-api\vendor\guzzlehttp\guzzle\src\Client.php:104
PHP  11. GuzzleHttp\Client->transfer() C:\inetpub\wwwroot\google-sheet-api\vendor\guzzlehttp\guzzle\src\Client.php:97
PHP  12. GuzzleHttp\HandlerStack->__invoke() C:\inetpub\wwwroot\google-sheet-api\vendor\guzzlehttp\guzzle\src\Client.php:268
PHP  13. GuzzleHttp\Middleware::GuzzleHttp\{closure}() C:\inetpub\wwwroot\google-sheet-api\vendor\guzzlehttp\guzzle\src\HandlerStack.php:67
PHP  14. GuzzleHttp\RedirectMiddleware->__invoke() C:\inetpub\wwwroot\google-sheet-api\vendor\guzzlehttp\guzzle\src\Middleware.php:57
PHP  15. GuzzleHttp\Middleware::GuzzleHttp\{closure}() C:\inetpub\wwwroot\google-sheet-api\vendor\guzzlehttp\guzzle\src\RedirectMiddleware.php:68
PHP  16. GuzzleHttp\PrepareBodyMiddleware->__invoke() C:\inetpub\wwwroot\google-sheet-api\vendor\guzzlehttp\guzzle\src\Middleware.php:30
PHP  17. Google\Auth\Middleware\ScopedAccessTokenMiddleware->Google\Auth\Middleware\{closure}() C:\inetpub\wwwroot\google-sheet-api\vendor\guzzlehttp\guzzle\src\PrepareBodyMiddleware.php:42
PHP  18. GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}() C:\inetpub\wwwroot\google-sheet-api\vendor\google\auth\src\Middleware\ScopedAccessTokenMiddleware.php:146
PHP  19. GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}() C:\inetpub\wwwroot\google-sheet-api\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php:51
PHP  20. GuzzleHttp\Handler\CurlHandler->__invoke() C:\inetpub\wwwroot\google-sheet-api\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php:28
PHP  21. GuzzleHttp\Handler\CurlFactory::finish() C:\inetpub\wwwroot\google-sheet-api\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php:43
PHP  22. GuzzleHttp\Handler\CurlFactory->release() C:\inetpub\wwwroot\google-sheet-api\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:107
PHP  23. count() C:\inetpub\wwwroot\google-sheet-api\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:67

## Steps to Reproduce the Problem

  1. follow the sample instructions
  

## Specifications

  - PHP version (`php -v`): 7.2.7
  - OS (Mac/Linux/Windows): Windows 10

**Comment by erickoledadevrel** [comment]
See issue #29.
