### ISSUE TITLE
Invalid parameter value for access_type: 'offline ' is not valid

### ISSUE THREAD

**Issue by joeybab3** [gsuitedevs/php-samples#44]
When using the sheets quickstart for php: https://developers.google.com/sheets/api/quickstart/php
I am able to install everything as required, running it gives me a url successfully, but going to that url for verification yields a 400 error with the message

**Error: invalid_request**
 ```
Invalid parameter value for access_type: 'offline ' is not valid
```

  - PHP: 7.2.9
  - OS: Windows

**Comment by erickoledadevrel** [comment]
It looks like you may have copied some extra whitespace which is causing a problem when the OAuth system is handling the URL. Please try again ensuring that you don't copy any extra characters.
