### ISSUE TITLE
Always said no connection available

### ISSUE THREAD

**Issue by rsRamgharia** [gsuitedevs/php-samples#50]
I am using quickkstart that is available in documentation, but it always said no connection available.
But when i try same credentials from javascript it works fine. 

if i am wrong somewhere please suggest me.

here is the link of code from documentation that i use in my projecrt

[https://developers.google.com/people/quickstart/php](https://developers.google.com/people/quickstart/php)

Thanku.

**Comment by erickoledadevrel** [comment]
Unfortunately that's not enough information to troubleshoot the issue. Please work to determine the exact error and stack trace.

**Comment by rsRamgharia** [comment]
Sorry to disturb you but i got the solution.
Thanku.😊
