### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by ronak1023** [gsuitedevs/php-samples#55]
(Please search [existing issues](https://github.com/gsuitedevs/php-samples/issues) before creating a new one.)

**Sample:**

## Steps to Reproduce the Problem

  1.
Fatal error: Uncaught Exception: This application must be run on the command line. in C:\xampp\htdocs\quickstart.php:5 Stack trace: #0 {main} thrown in C:\xampp\htdocs\quickstart.php on line 5
  1.
  1.

## Specifications

  - PHP version (`php -v`):
  - OS (Mac/Linux/Windows):

**Comment by asrivas** [comment]
Which quickstart was this for?

**Comment by asrivas** [comment]
I'm going to close this out but if you are still having the issue please let us know
