### ISSUE TITLE
Error on while entering code in command-line prompt

### ISSUE THREAD

**Issue by RayanAntony** [gsuitedevs/php-samples#57]
(Please search [existing issues](https://github.com/gsuitedevs/php-samples/issues) before creating a new one.)

**Sample:**

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - PHP version (`php -v`):
  - OS (Mac/Linux/Windows):

**Comment by RayanAntony** [comment]
PHP Warning:  count(): Parameter must be an array or an object that implements C
ountable in C:\xampp\htdocs\antony\quickstart\vendor\guzzlehttp\guzzle\src\Handl
er\CurlFactory.php on line 67

Warning: count(): Parameter must be an array or an object that implements Counta
ble in C:\xampp\htdocs\antony\quickstart\vendor\guzzlehttp\guzzle\src\Handler\Cu
rlFactory.php on line 67
No upcoming events found.

**Comment by erickoledadevrel** [comment]
See here for how to address this issue: https://github.com/gsuitedevs/php-samples/issues/29#issuecomment-455568302
