### ISSUE TITLE
I am getting "cURL error 60"

### ISSUE THREAD

**Issue by vibhajadwani** [gsuitedevs/php-samples#8]
Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\wamp\www\tripbuilder\google_sheet\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187

**Comment by grant** [comment]
@vibhajadwani Did following the link above solve the problem?

**Comment by erickoledadevrel** [comment]
Yes, duplicate of #19.
