### ISSUE TITLE
PHP Fatal error can't use mehod reun value in write context in .../quickstart.php on line 66

### ISSUE THREAD

**Issue by slong002** [gsuitedevs/php-samples#9]
PHP Fatal error:  Can't use method return value in write context in /var/www/html/mywebdirectory/quickstart.php on line 66

**Comment by grant** [comment]
Which sample is this for?

**Comment by slong002** [comment]
Php quickstart for Google calendar api.

**Comment by erickoledadevrel** [comment]
Thanks for reporting this problem. I've pushed a fix that should make the code compatible with PHP 5.4.
